### ISSUE TITLE
bug: problem when installing in the default node version in ubuntu 22 lts

### ISSUE THREAD

**Issue by jagalindo** [sebasruii/flamapy-ide#4]
just follow up the readme instructions and got this output 

flamapyide@flamapyide:~/flamapy-ide$ node setup.mjs 
file:///home/flamapyide/flamapy-ide/setup.mjs:6
const pyodide = await loadPyodide();
                ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
flamapyide@flamapyide:~/flamapy-ide$

**Comment by sebasruii** [comment]
@jagalindo Thanks for letting me know. It appears that this is caused by the default node version in ubuntu. FlamapyIDE currently runs on pyodide v0.26.2 and according to its [documentation](https://pyodide.org/en/stable/usage/index.html#node-js), Node.js < 18 is not officially supported. I am currently using node v20.15.1 and there are no issues when running the script.

You can check your nodejs version with `node -v` 

I would recommend updating you node version to its latest LTS version in case it is lower than 18.

**Comment by sebasruii** [comment]
I will update the installation guide to clarify this.

**Comment by jagalindo** [comment]
Having that dockerfile will certainly help

**Comment by sebasruii** [comment]
Happy to announce that now it is possible to deploy from a docker image! Instructions can be found on README.
